server:
  port: 8085
spring.cloud.stream:
  function:
    definition: userEventService
  bindings:
    userEventService-in-0:
      destination: users-topic
  kafka:
    streams:
      binder:
        configuration:
          spring.json.trusted.packages: '*' # Used to map deserializer object, so we do not need to put POJO in same package as producer class
    bindings:
      userEventService-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      userAddedEventService-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    binder:
      brokers:
        #        - localhost:9091
        - localhost:9092
spring:
  couchbase:
    bootstrap-hosts: localhost
    bucket:
      name: users
      password: 19011983
  data:
    couchbase:
      auto-index: true

logging:
  level:
    org.springframework.data.couchbase.repository.query: DEBUG