spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users-service
    username: postgres
    password: ale
spring.cloud.stream:
  function:
    definition: userAddEvent
  bindings:
    userAddEvent-out-0:
      destination: ${topic.name}
  kafka:
    bindings:
      userAddEvent-out-0:
        producer:
          configuration:
            value:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
    binder:
      brokers:
        - localhost:9091
        - localhost:9092
topic:
  name: users-topic